services:
  - type: worker
    name: fb-ads-worker
    env: node
    nodeVersion: 20
    branch: main
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node cron.js"
    envVars:
      - key: FB_ACCESS_TOKEN
        value: ""
      - key: FB_AD_ACCOUNTS
        value: ""
      - key: FB_APP_ID
        value: ""
      - key: FB_APP_SECRET
        value: ""
      - key: PG_URI
        value: ""
      - key: GOOGLE_SHEET_ID
        value: ""
      - key: GOOGLE_ADS_CUSTOMER_ID
        value: ""
      - key: GOOGLE_ADS_DEVELOPER_TOKEN
        value: ""
      - key: SLACK_WEBHOOK_URL
        value: ""
      - key: ERROR_ALERT_EMAIL
        value: ""
