envVarGroups:
  - name: adshub-env
    envVars:
      - key: FB_ACCESS_TOKEN
        value: ""
      - key: FB_BUSINESS_ID
        value: "1013395692075293"
      - key: FB_AD_ACCOUNTS
        value: "act_420838866444927,act_1538360642912126"
      - key: FB_APP_ID
        value: ""
      - key: FB_APP_SECRET
        value: ""
      - key: PG_URI
        value: ""
      - key: GOOGLE_SHEET_ID
        value: ""
      - key: GOOGLE_ADS_CUSTOMER_ID
        value: ""
      - key: GOOGLE_ADS_DEVELOPER_TOKEN
        value: ""
      - key: SLACK_WEBHOOK_URL
        value: ""
      - key: ERROR_ALERT_EMAIL
        value: ""
      - key: SYNC_API_KEY
        value: ""
      - key: REDIS_URL
        value: ""

services:
  - type: web
    name: fb-ads-web
    env: node
    nodeVersion: 20
    branch: main
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - fromGroup: adshub-env
  - type: worker
    name: fb-ads-worker
    env: node
    nodeVersion: 20
    branch: main
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node cron.js"
    envVars:
      - fromGroup: adshub-env
