name: adshub
services:
- name: web
  source_dir: /
  github:
    repo: jennyrsmith/AdsHub
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  build_command: |
    npm ci
    cd ui && npm ci && cd ..
    npm run build
    npm run init:admin
    npm run init:team
  envs:
  - key: NODE_ENV
    value: production
  - key: HOST
    value: 0.0.0.0
  - key: PORT
    value: "8080"
  - key: ADMIN_EMAIL
    value: jenny@beautybyearth.com
  - key: ADMIN_PASSWORD
    value: bBEHappy#120!ADS